name: job_manager
description: A new Flutter project.

publish_to: "none"

version: 0.1.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  animate_do: ^3.0.2
  cached_network_image: ^3.2.3
  cupertino_icons: ^1.0.5
  dio: ^4.0.6
  firebase_core: ^2.3.0
  flex_color_scheme: ^6.1.1
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.1.1
  flutter_svg: ^1.1.6
  geolocator: ^9.0.2
  google_maps_flutter: ^2.2.1
  http: ^0.13.5
  loading_overlay: ^0.3.0
  nb_utils: ^4.6.25
  pull_to_refresh: ^2.0.0
  velocity_x: ^3.6.0

dev_dependencies:
  flutter_launcher_icons: ^0.11.0
  flutter_lints: ^2.0.1

  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/icons/appicon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
